build_server_image:
  image: docker:20.10.16
  rules:
    - if: $CI_COMMIT_BRANCH
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $REGISTRY_TOKEN -p $REGISTRY_TOKEN $REGISTRY_URL
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME --build-arg motd="$CI_COMMIT_TITLE" .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME
# build_bungee_image:
#   image: docker:20.10.16
#   rules:
#     - if: $CI_COMMIT_BRANCH
#   services:
#     - docker:20.10.16-dind
#   before_script:
#     - docker login -u $REGISTRY_TOKEN -p $REGISTRY_TOKEN $REGISTRY_URL
#   script:
#     - docker build -t registry.digitalocean.com/humin-game-lab/bungee-server:$CI_COMMIT_REF_NAME --file Dockerfile.bungee .
#     - docker push registry.digitalocean.com/humin-game-lab/bungee-server:$CI_COMMIT_REF_NAME
