FROM maven:3.9.2-eclipse-temurin-17

WORKDIR /server

ARG base_world_url=https://minecraft-hgl-drew.s3.amazonaws.com/
ARG world_file_name=world.zip
ARG conveyor_url=https://minecraft-hgl-drew.s3.amazonaws.com/conveyor.zip
ARG spigot_url=https://minecraft-hgl-drew.s3.amazonaws.com/spigot.jar
ARG motd="Local Dev Server"

# Install wget
RUN apt-get update && apt-get install -y wget

# Install git
RUN apt-get update && apt-get install -y git

# Install unzip
RUN apt-get update && apt-get install -y unzip

# Install zsh
RUN apt-get update && apt-get install -y zsh

# Download spigot.jar
RUN wget -O ./spigot.jar $spigot_url

EXPOSE 25565/udp
EXPOSE 25565/tcp
EXPOSE 25575/tcp

RUN ["java", "-Xms1024M", "-Xmx2048M", "-Dfile.encoding=UTF-8", "-jar", "spigot.jar", "--world-dir", "./worlds", "nogui"]

# Change eula to true
RUN sed -i 's/false/true/g' eula.txt 

# Set the MOTD in server.properties
RUN sed -i "s/motd=A Minecraft Server/motd=${motd}/g" server.properties

# Increase max players
RUN sed -i "s/max-players=20/max-players=100/g" server.properties


RUN mkdir ./plugins

COPY ./start.sh ./start.sh
RUN chmod +x ./start.sh

COPY ./build_portal.sh ./build_portal.sh
RUN find . -name "*.sh" -exec chmod +x {} \;
# Replace line endings for linux
RUN find . -name "*.sh" -exec sed -i 's/\r$//' {} \;

# Conditionally download worldedit and voxel sniper based on the build args
ARG voxel_sniper_url=https://minecraft-hgl-drew.s3.amazonaws.com/VoxelSniper-6.1.2.jar
ARG worldedit_url=https://minecraft-hgl-drew.s3.amazonaws.com/worldedit-bukkit-7.2.14.jar
ARG edit_tools_enabled

RUN if [ "$edit_tools_enabled" = "true" ] ; then \
    wget -O ./plugins/VoxelSniper.jar $voxel_sniper_url ; \
    wget -O ./plugins/worldedit.jar $worldedit_url ; \
    fi

ARG install_tmux
RUN if [ "$install_tmux" = "true" ] ; then \
    apt-get update && apt-get install -y tmux ; \
    fi

# Open a shell 
CMD ["/bin/zsh"]
