version: "3"

services:
  server:
    build:
      context: .
      args:
        - edit_tools_enabled=false # Change to true to enable WorldEdit and VoxelSniper
        - install_tmux=true
      dockerfile: Dockerfile.dev
    ports:
      - "25565:25565"
    volumes:
      - type: bind
        source: ./plugins
        target: /plugins
    stdin_open: true
    tty: true
