version: "3"
services:
  server:
    image: "registry.digitalocean.com/humin-game-lab/mc-server:main"
    # FOR USE WITH LOCAL DEVELOPMENT
    # build:
    #   context: .
    stdin_open: true
    tty: true
    environment:
      - MAX_PLAYERS=1
  # bungee:
  #   networks:
  #     - mc
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.bungee
  #   ports:
  #     - "25565:25577"
